# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        
        Form.resize(255, 268)
        Form.setStyleSheet("QWidget {\n"
"   background-color: #70a932\n"
"}\n"
"\n"
"QPushButton {\n"
"   background-color: #25221d;\n"
"   color: #fff;\n"
"   font-weight: 600\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #fff;\n"
"   color: #000000\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"QLabel {\n"
"   font-weight: 600\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.IP_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.IP_Label.setObjectName("IP_Label")
        self.verticalLayout.addWidget(self.IP_Label)
        self.IP_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IP_Edit.setText("")
        self.IP_Edit.setObjectName("IP_Edit")
        self.verticalLayout.addWidget(self.IP_Edit)
        self.Tip_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Tip_Label.setObjectName("Tip_Label")
        self.verticalLayout.addWidget(self.Tip_Label)
        self.Nomer_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Nomer_Edit.setObjectName("Nomer_Edit")
        self.verticalLayout.addWidget(self.Nomer_Edit)
        self.Nomer_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Nomer_Label.setObjectName("Nomer_Label")
        self.verticalLayout.addWidget(self.Nomer_Label)
        self.Tip_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Tip_Edit.setObjectName("Tip_Edit")
        self.verticalLayout.addWidget(self.Tip_Edit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.IP_Label.setText(_translate("Form", "IP"))
        self.Tip_Label.setText(_translate("Form", "Тип оборудования"))
        self.Nomer_Label.setText(_translate("Form", "Серийный номер ONU"))
        self.pushButton.setText(_translate("Form", "Отправить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
