# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.resize(255, 280)
        MainWindow.setStyleSheet("QWidget {\n"
"   background-color: #70a932\n"
"}\n"
"\n"
"QPushButton {\n"
"   background-color: #25221d;\n"
"   color: #fff;\n"
"   font-weight: 600\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #fff;\n"
"   color: #000000\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #fff\n"
"}\n"
"\n"
"QLabel {\n"
"   font-weight: 600\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 201, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.IP_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.IP_Label.setObjectName("IP_Label")
        self.verticalLayout.addWidget(self.IP_Label)
        self.IP_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IP_Edit.setText("")
        self.IP_Edit.setObjectName("IP_Edit")
        self.verticalLayout.addWidget(self.IP_Edit)
        self.Tip_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Tip_Label.setObjectName("Tip_Label")
        self.verticalLayout.addWidget(self.Tip_Label)
        self.Nomer_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Nomer_Edit.setObjectName("Nomer_Edit")
        self.verticalLayout.addWidget(self.Nomer_Edit)
        self.Nomer_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Nomer_Label.setObjectName("Nomer_Label")
        self.verticalLayout.addWidget(self.Nomer_Label)
        self.Tip_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Tip_Edit.setObjectName("Tip_Edit")
        self.verticalLayout.addWidget(self.Tip_Edit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 255, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.IP_Label.setText(_translate("MainWindow", "IP"))
        self.Tip_Label.setText(_translate("MainWindow", "Тип оборудования"))
        self.Nomer_Label.setText(_translate("MainWindow", "Серийный номер ONU"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
